-- AlterTable
ALTER TABLE "public"."Profesional_data" ALTER COLUMN "fake_name" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "birth_date" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "local_id" DROP NOT NULL,
ALTER COLUMN "cv_file" DROP NOT NULL,
ALTER COLUMN "cv_link" DROP NOT NULL,
ALTER COLUMN "avatar" DROP NOT NULL;
